### ISSUE TITLE
con not  login with vscode (WSL)

### ISSUE THREAD

**Issue by Muchmorepig** [codota/tabnine-sublime#112]
**please complete the following information:**	
 - OS version: WSL1	
 - Editor version: vscode	
 - Programming language: 
 - Tabnine extension version:3.4.26

**Issue Details:**
![image](https://user-images.githubusercontent.com/68462246/132159684-cdbbc3e3-8ebe-4444-a63f-d462e947c4e8.png)

gz#6099

**Comment by bilucodota** [comment]
Hi @Muchmorepig 
Try to follow this https://github.com/codota/tabnine-vscode/issues/572 and let me know if it works for you

**Comment by Muchmorepig** [comment]
thanks a lot ! It works(define a $BROWSER)
