### ISSUE TITLE
TabNine not showing up in package control install package

### ISSUE THREAD

**Issue by mukhinv** [codota/tabnine-sublime#51]
Hello,

TabNine is not showing up in the Package Control, below is the screenshot:

![image](https://user-images.githubusercontent.com/46717607/76747124-b69acc00-6789-11ea-93ef-fb5151b2fe7a.png)

I am able to install my other Sublime Text 3 packages without any issue.

**Comment by martinbaranek** [comment]
Stupid question - have you checked, whether it is not already installed?
if you could attach screenshot of Package Control: List packages and search tab?

**Comment by kickthedragon** [comment]
I can confirm this as well.  I have to clone it manually into my Packages folder

<img width="600" alt="Screen Shot 2020-08-28 at 1 38 43 PM" src="https://user-images.githubusercontent.com/5422123/91609069-f1f21700-e933-11ea-96c4-b67994faee60.png">

<img width="600" alt="Screen Shot 2020-08-28 at 1 38 51 PM" src="https://user-images.githubusercontent.com/5422123/91609026-e141a100-e933-11ea-84b1-3036ca3f2a7c.png">

**Comment by boaz-codota** [comment]
Solved
