### ISSUE TITLE
v2.5.1 Error with sublime 3 3211

### ISSUE THREAD

**Issue by martinbaranek** [codota/tabnine-sublime#52]
After fresh install of Sublime 3 v3211 and package TabNine 2.5.1,
i got error:
Started TabNine v2.5.1
Failed to communicate with TabNine subprocess: No JSON could be decoded
(i forgot to save the error).
and this goes over and over.
Tried to manually clone repo with 2.5.1, same error.
Issue fixed with installing older version - TabNine v2.2.2 and denying write access to binaries (to stop auto-update). 2.2.2 seems to be working, no error in sublime console.

**Comment by amircodota** [comment]
Thank you for reporting this.

Which os are you using?

**Comment by martinbaranek** [comment]
Win 10 1903 Ultimate. Python 3.7 installed only (without Anaconda)

**Comment by amircodota** [comment]
It would be great if you can download the latest tabnine binary [here](https://update.tabnine.com/2.5.1/x86_64-pc-windows-gnu/TabNine.exe).
You can download it to any folder you want.

Run it on the command line. If it works correctly it should just sit waiting for user input.

Paste this as its input

```
{"request":{"Autocomplete":{"before":"tabnine::version","after":"","filename":"a.js","region_includes_beginning":true,"region_includes_end":true,"max_num_results":5}},"version":"2.0.2"}
```

If it works correctly, it should return a json containing 2.5.1 as the version.

It it emits an error at any point, paste it here, and we'll take it from there.

Thanks a lot!

**Comment by martinbaranek** [comment]
I've tried to run it in powershell (admin mode and non-admin mode) and instantly after i ran ./TabNine.exe it started returning:
PdhCollectQueryData error: 800007d5 0x13ba1c0
repeatedly.

**Comment by amircodota** [comment]
Just to make sure, can you run it in the regular windows command line and not in powershell?

It is more similar to how it is run from an editor

Thanks

**Comment by martinbaranek** [comment]
![image](https://user-images.githubusercontent.com/36608613/77088693-1ea91680-6a05-11ea-9258-ce9d2228ebb3.png)
Here you go.

**Comment by amircodota** [comment]
One more thing - 
Can you close all editors that have a tabnine plugin, then run again from the command line, and see how many tabnine processes you see? There should be two

Thanks

**Comment by martinbaranek** [comment]
Yes, works. After launching the .exe, two TabNine.exe show up in task manager.

**Comment by amircodota** [comment]
But the error persists, right?

**Comment by martinbaranek** [comment]
Yes, still the same error. Does not matter whether cmd/powershell.

**Comment by amircodota** [comment]
Thank you for your input. Investigating this error.

Could this be a permissions issue? Is your user limited in some way that you are aware of?

**Comment by martinbaranek** [comment]
Not really, the cmd i've sent was run under admin privileges. Running just basic windows defender AV, and 2.2.2 version works just fine.

**Comment by amircodota** [comment]
Yes, the code that uses the PdhCollectQueryData was added in 2.3.

Can you run the windows command line "as administrator" and see if it works?

**Comment by martinbaranek** [comment]
Is there any "intermediate" version (like 2.5.0) binary, so i could check when the bug appears? (I'm git beginner, I've found just the 2.2.2)

**Comment by martinbaranek** [comment]
Already done, does not work. (Check the image i've sent before, it's Admin: command prompt)

**Comment by amircodota** [comment]
@martinbaranek I'm pretty sure it will reproduce with [2.3.2](https://update.tabnine.com/2.3.2/x86_64-pc-windows-gnu/TabNine.exe).

Can you try running the windows command line "as administrator" and see if it fixes the issue?

**Comment by martinbaranek** [comment]
Nope, does not work.

**Comment by martinbaranek** [comment]
Oh, nevermind, the 2.3.2 works.
![image](https://user-images.githubusercontent.com/36608613/77090373-56b15900-6a07-11ea-8d44-575643b0adbb.png)

**Comment by amircodota** [comment]
what about [2.3.7](https://update.tabnine.com/2.3.7/x86_64-pc-windows-gnu/TabNine.exe)?

**Comment by martinbaranek** [comment]
2.3.7 throws the same error as 2.5.1.
So it's definitely between 2.3.2 and 2.3.7

**Comment by amircodota** [comment]
I'm guessing TabNine.exe has a [lower integrity level](https://superuser.com/questions/163361/are-processes-launched-by-elevated-processes-themselves-elevated/163395) because it was downloaded, and so does not inherit the administrator priveleges.

Can you try using a tool like [chml](https://www.minasi.com/apps/) to check the TabNine.exe integrity level and change it?

**Comment by martinbaranek** [comment]
![image](https://user-images.githubusercontent.com/36608613/77093152-e4427800-6a0a-11ea-970a-ddb7c39dac8e.png)

**Comment by amircodota** [comment]
Can you temporarily lower [UAC](https://www.howtogeek.com/howto/windows-vista/disable-user-account-control-uac-the-easy-way-on-windows-vista/) and see if it fixes the issue?

**Comment by martinbaranek** [comment]
I have UAC turned off completely since the beginning.

**Comment by amircodota** [comment]
Oh, that changes everything :-)

Can you open perfmon, and try to monitor %CPU for the TabNine process? 
(I can send moredetailed instructions if needed)

**Comment by martinbaranek** [comment]
On i5-7200u (2 cores, 4 threads)
2.5.1 exe:
Error, 15% CPU.
+ Console window host (probably due to high refresh rate with errors): 22% CPU (single core almost fully loaded)
2.3.2 exe:
No error, 0% cpu usage (probably waiting for json)

**Comment by amircodota** [comment]
OK, Thank you.

I'll try to reproduce it on my own windows machine with all the data you gave me.
Hope I can fix it soon, I'll keep you updated

**Comment by martinbaranek** [comment]
Great! If you need any testing, I'm available most of the time.

**Comment by amircodota** [comment]
Great!

Thanks a lot for all your help and responsiveness.

One last question - are you an administrator of the machine you are running on?

**Comment by martinbaranek** [comment]
I am not logged in as the "hidden windows superadmin", but i have admin privileges, and ran all the commands from admin command prompt (cmd -> run as admin)

**Comment by amircodota** [comment]
Sorry, one more thing.

Can you run `TabNine --inner` and see if this way it works?

**Comment by martinbaranek** [comment]
Yes, it works on 2.5.1! No error, returns
{"old_prefix":"","results":[{"new_prefix":"2.5.1","old_suffix":"","new_suffix":""}],"user_message":[],"docs":[]}

**Comment by amircodota** [comment]
I'll explain what's going on, and maybe you can figure out what's going on on your machine.

When you run TabNine, it is basically a monitor process.
It runs `TabNine --inner` as a child process, and monitors it for CPU, using performance counters.

I tested it on my windows 10 machine, as an admin user and a regular user, with UAC enabled or disabled. On my machine it always seem to work.

On your machine, trying to collect performance counter returns PDH_NO_DATA (0x800007D5).
According to [the docs](https://docs.microsoft.com/en-us/windows/win32/api/pdh/nf-pdh-pdhcollectquerydata), this might happen when running without an elevated token, but you have UAC disabled and you are an admin, so that does not seem to be the case.

Any idea what's different between our machines? Maybe you have some security software that recognizes this is a downloaded binary and limits its access or something like that?

**Comment by martinbaranek** [comment]
Ah, I have just found out - I am sorry for misleading info - i have disabled notifications about UAC, but not UAC itself. Maybe is that a difference?
![image](https://user-images.githubusercontent.com/36608613/77115526-cab32780-6a2e-11ea-821c-7454d3b20c11.png)
![image](https://user-images.githubusercontent.com/36608613/77115542-d1da3580-6a2e-11ea-92d0-f9c835a6cf7b.png)

**Comment by amircodota** [comment]
To my knowledge, that is how you disable UAC.
I know the wording is "disable notifications" but I think it actually means "Do not block when...".

**Comment by amircodota** [comment]
Any other security software there? Antivirus? something else?

**Comment by martinbaranek** [comment]
No, only Windows defender. I treid to disable it completely, did not help.
![image](https://user-images.githubusercontent.com/36608613/77115897-752b4a80-6a2f-11ea-84f7-6465c667df6b.png)
There was a security warning on the file, but i checked it, the security disappeared, but still not working.

**Comment by amircodota** [comment]
I can start sending you binaries disabling some code, to check exactly which line of code causes the error.
It will require probably some back and forth several times, to nail the exact line of code.
Will that work for you?

**Comment by martinbaranek** [comment]
OK. I've maybe found the problem, and you're probably not in fault in here:
![image](https://user-images.githubusercontent.com/36608613/77116207-14e8d880-6a30-11ea-8a93-4c53d083672b.png)
I have never seen this before. I will do reboot (since I am so stupid i haven't done it before i posted it here :( ) and will give you results.

**Comment by amircodota** [comment]
maybe [this](https://answers.microsoft.com/en-us/windows/forum/windows_7-performance/perfmon-problems-unable-to-add-counters/e90f231d-0014-457d-8b1f-5f342971597a) will help?

**Comment by martinbaranek** [comment]
> maybe [this](https://answers.microsoft.com/en-us/windows/forum/windows_7-performance/perfmon-problems-unable-to-add-counters/e90f231d-0014-457d-8b1f-5f342971597a) will help?

On second attempt, restoring the values doing that tutorial fixed problems in performance monitor and also fixed running TabNine (2.5.1 now does not throw errors and returns nice JSON).

I am really sorry that my crappy windows took so much of your time. I don't know, what caused it.
I will try to reinstall it in Sublime and will close this thread if it works. THanks for your help!

**Comment by amircodota** [comment]
Glad to hear!

Do not worry about it - I'm pretty sure you are not the only one with this issue.
On my end, I'll try to reproduce, and see if I can recognize the situation in code, and make sure TabNine functions even in such a case.

Thanks for all your feedback and troubleshooting

**Comment by martinbaranek** [comment]
Everything works, TabNine auto updated to 2.5.1, config web browser window successfuly opens.

So it was the bad pointers so system wasnt able to read memory/CPU data.
cmd lodctr /r fixed it.
