### ISSUE TITLE
v2.5.1 No JSON object could be decoded; failed to add counter 'tot_0': c0000bb9...

### ISSUE THREAD

**Issue by mc-aze** [codota/tabnine-sublime#53]
After fresh install of Sublime 3 v3211 and package TabNine 2.5.1,
error:
Started TabNine v2.5.1
Failed to communicate with TabNine subprocess: No JSON could be decoded

if i run Sublime Text 3\Packages\TabNine\binaries\2.5.1\x86_64-pc-windows-gnu\TabNine.exe i get

failed to add counter 'tot_0': c0000bb9...
failed to add counter 'tot_1': c0000bb9...
failed to add counter '0_0': c0000bb9...
failed to add counter '0_1': c0000bb9...
failed to add counter '1_0': c0000bb9...
failed to add counter '1_1': c0000bb9...
failed to add counter '2_0': c0000bb9...
failed to add counter '2_1': c0000bb9...
failed to add counter '3_0': c0000bb9...
failed to add counter '3_1': c0000bb9...
failed to add counter '4_0': c0000bb9...
failed to add counter '4_1': c0000bb9...
failed to add counter '5_0': c0000bb9...
failed to add counter '5_1': c0000bb9...
failed to add counter '6_0': c0000bb9...
failed to add counter '6_1': c0000bb9...
failed to add counter '7_0': c0000bb9...
failed to add counter '7_1': c0000bb9...
failed to add counter 'net0_out': c0000bb9...
failed to add counter 'net1_out': c0000bb9...

this issue is similar to: https://github.com/codota/tabnine-sublime/issues/52#issue-584337388
from that issue i tried:

1. latest tabnine binary but i get the same error
2. correctly returns a json containing 2.5.1 as the version
![tabnine](https://user-images.githubusercontent.com/62522708/77262180-04747000-6c73-11ea-855d-7358c6da142b.PNG)

3. running cmd as admin but the error persist
4. correctly shows two process of TabNine.exe 
5. binary 2.3.2 doesnt show the error
6. binary 2.3.7 shows the error
7. chml into tabnine.exe version 2.3.7 shows the same error 
![tabnine_chml](https://user-images.githubusercontent.com/62522708/77262183-09392400-6c73-11ea-80ec-76642d477fa3.PNG)

8. I have UAC turned off completely since the beginning and i have admin privileges
9. Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz, 2601 Mhz, 4 cores (2 logical cores per physical)
10. TabNine.exe --inner doesnt show the error
11. lodctr /r didnt fix the error, lodctr /q shows everything enabled
12. restart windows doesnt fix
13. config web browser window opens most of the time. Sometimes conection gets rejected. (ERR_CONNECTION_REFUSED using chrome)
14. bitdefender doesnt show anything wrong

https://docs.microsoft.com/en-us/windows/win32/sysmon/counters-add shows the error code

**Comment by amircodota** [comment]
Thanks you for the detailed report, @mc-aze 

[Error c0000bb9](https://docs.microsoft.com/en-us/windows/win32/perfctrs/pdh-error-codes) means PDH_CSTATUS_NO_COUNTER, so it fails to find the relevant counter.

Can you open perfmon, and see if you can add the following counter

Processor/% Processor Time/_Total

This is one of the counters that it tries to check, so maybe perfmon will give us a clue into what's going on.

**Comment by amircodota** [comment]
@mc-aze I suspect it is related to the fact your perf counters names are in spanish.
We do use [PdhLookupPerfNameByIndexW](https://docs.microsoft.com/en-us/windows/win32/api/pdh/nf-pdh-pdhlookupperfnamebyindexw) to translate it to the correct name, but I suspect something there might go wrong.

Do you thing it would be ok if I sent you a private build with some debug prints?

**Comment by mc-aze** [comment]
yes, im happy to help

**Comment by amircodota** [comment]
@mc-aze 

Can you paste what you have in your registry under HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Perflib\009\Counter?

009 is for english. Do you have another entry other then 009? Can you paste its value too?

**Comment by mc-aze** [comment]
![image](https://user-images.githubusercontent.com/62522708/77465937-39ee9a00-6de8-11ea-962f-db56c8f57a4c.png)


HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Perflib\009\Counter
[009.txt](https://github.com/codota/tabnine-sublime/files/4377137/009.txt)

HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Perflib\CurrentLanguage\Counter
[currentlanguage.txt](https://github.com/codota/tabnine-sublime/files/4377138/currentlanguage.txt)

HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Perflib\00A\Counter
[00A.txt](https://github.com/codota/tabnine-sublime/files/4377152/00A.txt)

**Comment by amircodota** [comment]
Very strange, 009 key should always be in english to my knowledge.
On your machine it is in spanish, and therefore, we fail to translate The english name to the localized name.

Is this a spanish version of windows 10?

Invstigating...

**Comment by amircodota** [comment]
@mc-aze 

[Here](https://amir-public-code.s3.amazonaws.com/TabNine.exe) is a private test build.

Can you download it and run from command line?
Paste back what is the output?

**Comment by mc-aze** [comment]
im sorry, it was in english
[009_.txt](https://github.com/codota/tabnine-sublime/files/4377760/009_.txt)

this is the output of the private test build.
![image](https://user-images.githubusercontent.com/62522708/77478937-9c05ca00-6dfd-11ea-8c33-360b0c8f74f1.png)

**Comment by amircodota** [comment]
So it succeeds in translating `Processor` but fails to translate `% Processor Time`.

I've created a workaround - can you test?

Download the binary from [here](https://amir-public-code.s3.amazonaws.com/TabNine.exe).
When you run it, you should see no errors.
If you open Task manager, you should see only one TabNine.exe process running, instead of two.

**Comment by mc-aze** [comment]
![image](https://user-images.githubusercontent.com/62522708/77538788-0f9beb80-6e7f-11ea-808e-25d94f6646c5.png)

you are right

**Comment by amircodota** [comment]
@mc-aze 

Thank you for your help.

This fix will be released in the next tabnine release - within a few days most likely.

Note that this fix means that tabnine will work, but it runs without its watchdog, so monitoring memory and cpu will not work.

I'll let you know when this fix is available.

**Comment by amircodota** [comment]
Just released TabNine 2.6.0, that fixes this issue.

@mc-aze can you verify?

**Comment by mc-aze** [comment]
it works now.

do you need me to check anything?

![image](https://user-images.githubusercontent.com/62522708/78591482-7c18d200-7811-11ea-8153-893ec2068967.png)

thanks

**Comment by amircodota** [comment]
cool, glad to hear it works.
No need to test anything else.
