### ISSUE TITLE
Don't show recommendation box

### ISSUE THREAD

**Issue by konioyxgq** [codota/tabnine-sublime#57]
My tabnine, seems to be running, but just doesn't show the recommendation box.
What should I do?

**Comment by konioyxgq** [comment]
![image](https://user-images.githubusercontent.com/43984411/80070346-662b4100-8575-11ea-969f-43c42fecadde.png)
![image](https://user-images.githubusercontent.com/43984411/80070374-72170300-8575-11ea-869f-5657b8672552.png)

**Comment by amircodota** [comment]
@konioyxgq What type of project do youhave? What programming language?

**Comment by konioyxgq** [comment]
python programming language

**Comment by konioyxgq** [comment]
I use python and C++ are the same situation.

**Comment by amircodota** [comment]
According to the log, it seems tabnine is working normally.

Can you open sublime console (ctrl+`), and see if there are errors on the sublime side?

**Comment by konioyxgq** [comment]
There's a little mistake, how it's going to be solved.
Thank you so much！
![image](https://user-images.githubusercontent.com/43984411/80471140-9019a480-8975-11ea-9ae4-19b0af1dc3c7.png)

**Comment by konioyxgq** [comment]
**Exception while interacting with TabNine subprocess: No JSON object could be decoded**

**Comment by amircodota** [comment]
It seems the tabnine subprocess returns the wrong output, which causes the sublime plugin to kill and restart the subprocess.

Under where the sublime package is installed (different places for different oses) there's a TabNine.py file.

Can you find the line that says 

`print("Exception while interacting with TabNine subprocess:", e)`

and change it to 

`print("Exception while interacting with TabNine subprocess:", e, result)`

Then re-try to use tabnine, and check the sublime console again

**Comment by konioyxgq** [comment]
Exception while interacting with TabNine subprocess: No JSON object could be decoded failed to add counter 'tot_0': c0000bb8...
![image](https://user-images.githubusercontent.com/43984411/81245136-d2627600-9046-11ea-8d0c-60983fd563b5.png)

**Comment by amircodota** [comment]
@konioyxgq 

TabNine uses a library that prints out errors.
Since TabNine to plugin communication is based on stdin/stdout, this messes up the protocol.

I'll try to reproduce internally and provide a fix.

**Comment by amircodota** [comment]
@konioyxgq  I was not able to reproduce, but I have a pretty good handle of what is goind on, and I've made a fix.

Any chance I can provide you with a build of TabNine that you can test?

**Comment by konioyxgq** [comment]
OK！Thank you so much！
Can you send me my e-mail? Or any other convenient way for you.
My e-mail is xgqkonioy@gmail.com

**Comment by konioyxgq** [comment]
Thank you very much. Now TabNine is working. That's cool！

**Comment by amircodota** [comment]
@konioyxgq Glad to hear. The fix is already in beta, and should be released to all users within a few days,
