### ISSUE TITLE
Autocompleting without hitting Tab

### ISSUE THREAD

**Issue by IPWright83** [codota/tabnine-sublime#63]
- Ubuntu 18.04 LTS
 - SublimeText 3 Build 3120	
 - JavaScript
 - TabNine extension version: 2.8.6
--
As I understood it TabNine should auto-complete when I press tab. However I'm frequently finding that as I type 3 characters, it then auto completes when I don't want it to and even when the match is quite poor. It should only be auto completing if I hit tab.

Is there a way to stop this behaviour? I want TabNine as an extra feature to use, not something that gets in the way of typing.
 
![Peek 2020-07-03 19-46](https://user-images.githubusercontent.com/1374775/86492415-fb149c80-bd65-11ea-94a6-4715f0e6a093.gif)

**Comment by amircodota** [comment]
@IPWright83 This sounds like a bug to me. Tabnine should only ever complete when you hit tab.

**Comment by IPWright83** [comment]
@amircodota thanks, if there's any more info I can provide let me know.

**Comment by IPWright83** [comment]
Are there any notes on how you can run TabNine with some more debugging? I keep turning it on wanting to use it more, but everytime I hit this bug (which is quite frequently) I unfortunately have to abandon it as it's almost impossible to workaround properly.

**Comment by amircodota** [comment]
@IPWright83 you can try debugging the plugin yourself, if you have the time.
We would certainly appreciate it :-)

I can provide setup instructions, if you want to go down that path

**Comment by IPWright83** [comment]
Yeah, that'd be good if you don't mind. I'm not a Python dev but I'm sure if I can add a breakpoint somehow and do some debugging I've got a fighting chance of working out what's happenning.

**Comment by amircodota** [comment]
I added [a page to the wiki](https://github.com/codota/tabnine-sublime/wiki/Debugging).

This is an initial version of the page, so any feedback on it is also welcome.

Good luck

**Comment by IPWright83** [comment]
@amircodota ok so here's an example that's auto completing without me hitting Tab.

![image](https://user-images.githubusercontent.com/1374775/88057260-beb0b100-cb59-11ea-8768-343fa6975ed1.png)

If I press `g` then that'll auto complete to the first suggested result (which might be ok in this instance - but obviously sometimes the behaviour gets in the way). 

I added logging of the `command_name` and the insertion event and I can see the following happens:
> tab_nine_leader_key
Inserting completion
tab_nine_substitute

So whatever the `tab_nine_leader_key` is, I'm guessing is triggering this to occur.

**Comment by IPWright83** [comment]
Hmm, I can see this defined in the default key mapping - however it's definitely not tab that I'm pressing.
```
{ "keys": ["tab"], "command": "tab_nine_leader_key", "context": [ { "key": "tab_nine_leader_key_available", "operator": "equal", "operand": true }] },
```

**Comment by amircodota** [comment]
@IPWright83 Any chance you have another plugin or something that changes the key bindings, like vim key bindings or something like that?

**Comment by IPWright83** [comment]
@amircodota not that I'm aware of - I've just tried disabling a bunch a few of the bigger ones and it seems to still behave that way.

I've got a bunch of keybindings myself, but nothing that I think should inteferre:

```
[
    { "keys": ["ctrl+d"], "command": "run_macro_file", "args": {"file": "res://Packages/Default/Delete Line.sublime-macro"} },
    { "keys": ["ctrl+shift+r"], "command": "reindent" , "args": { "single_line": false } },
    { "keys": ["ctrl+alt+p"], "command": "prompt_select_workspace" },
    { "keys": ["ctrl+alt+left"], "command": "jump_back" },
    { "keys": ["ctrl+alt+right"], "command": "jump_forward" },
    { "keys": ["ctrl+alt+d"], "command": "git_gutter_diff_popup" },
    { "keys": ["ctrl+alt+s"], "command": "gs_show_status" },
    { "keys": ["alt+up"], "command": "git_gutter_next_change" },
    { "keys": ["alt+down"], "command": "git_gutter_prev_change" },
    {
        "keys": ["g"],
        "command": "gs_custom",
        "args": {
            "args": ["pull"],
            "output_to_panel": true,
            "start_msg": "Starting pull",
            "complete_msg": "Pull complete.",
        },
        "context": [
            { "key": "setting.command_mode", "operator": "equal", "operand": false },
            { "key": "setting.git_savvy.status_view", "operator": "equal", "operand": true },
        ]
    },
    { "keys": ["ctrl+alt+f"], "command": "find_results_buffer_utils", "args": {"action": "focus_buffer"}, "context": [{"key": "is_find_results_buffer_open"}] },
    { "keys": ["ctrl+shift+p"], "command": "show_overlay", "args": {"overlay": "command_palette"} },
    { "keys": ["ctrl+shift+."], "command": "show_overlay", "args": {"overlay": "command_palette"} },
]

```

**Comment by amircodota** [comment]
@IPWright83 Can you send a list of all sublime packages you have installed?

**Comment by IPWright83** [comment]
@amircodota sure, didn't realise these were easy to get at:

```
"A File Icon",
"Babel",
"BetterFindBuffer",
"CFML",
"CloudFormation Validation",
"DiffTabs",
"DocBlockr",
"Dockerfile Syntax Highlighting",
"FindResultsBufferUtils",
"Floobits",
"Git Conflict Resolver",
"GitGutter",
"GitSavvy",
"JsPrettier",
"LESS",
"Less2Css",
"Package Control",
"PackageResourceViewer",
"SublimeLinter",
"SublimeLinter-contrib-xo",
"SublimeLinter-contrib-yamllint",
"SublimeLinter-eslint",
"SublimeLinter-json",
"SyncedSideBar",
"TabNine",
"Text Pastry",
"Theme - Soda",
"TodoReview",
"TypeScript",
"TypeScript Syntax",
"WordHighlight"
```

**Comment by IPWright83** [comment]
@amircodota well, that was interesting...

I've been looking at the other GitHub issue about remapping the shortcut key so it doesn't interfere with snippets which is a real pain. So opened my settings and saw this:

```
{ "keys": ["g"], "command": "tab_nine_leader_key", "context": [ { "key": "tab_nine_leader_key_available", "operator": "equal", "operand": true }] }
```

I have no idea how that got there (I don't remember ever setting it + have re-installed the package), but I believe that explains all the weirdness going on!

**Comment by amircodota** [comment]
Glad you were able to figure it out :+1:

**Comment by IPWright83** [comment]
Thanks @amircodota - sorry to have wasted some of your time, but I appreciate the help in debugging as I would never have thought to look in there (on the basis I thought I'd never changed it!).
