### ISSUE TITLE
TabNine not suggesting auto completions

### ISSUE THREAD

**Issue by IPWright83** [codota/tabnine-sublime#72]
- OS version: Ubuntu 18.04.4
 - Editor version: Sublime Text 3 Build 3210
 - Programming language: JavaScript
 - TabNine extension version: 3.0.6
 
 **If the issue is related to TabNine failure, please provide log files:**	

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

**Issue Details:**
TabNine stops working - there are no suggestions in the auto complete:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 627, in on_activated_async
    callback.on_activated_async(v)
  File "/home/iw651/.config/sublime-text-3/Packages/TabNine/completions/completions_v2.py", line 204, in on_activated_async
    }
  File "/home/iw651/.config/sublime-text-3/Packages/TabNine/tab_nine_process.py", line 116, in request
    req += '\n'
AttributeError: 'NoneType' object has no attribute 'dumps'
```

**Comment by dimacodota** [comment]
@IPWright83  can you please open the Sublime Console (`View -> Show Console`) and run the following code:
`import json; json.__file__`  ?

**Comment by IPWright83** [comment]
I get this output

**Comment by dimacodota** [comment]
Thank you  @IPWright83 . I will keep you posted. does it reproduce after restart?

**Comment by davidhariri** [comment]
Seeing this too. No completions.

**Comment by dimacodota** [comment]
@IPWright83 , I wasn't able to reproduce the issue, however, version 3.0.7 is trying to fix it, please confirm if the issue is resolved. 
Thanks

**Comment by davidhariri** [comment]
> @IPWright83 , @davidhariri - I wasn't able to reproduce the issue, however, version 3.0.7 is trying to fix it, please confirm if the issue is resolved.
> Thanks

The most recent update has resolved my issue. Thanks @dimacodota 👏

**Comment by dimacodota** [comment]
Great! closing the issue

**Comment by jsheebs104** [comment]
What about parameter/argument doc suggestions? Is this even a feature with TabNine? Because tab + anything or nothing does not work in any IDE or TE in any way, shape, or form whatsoever.
