### ISSUE TITLE
Suggestion when selecting remove part of the word

### ISSUE THREAD

**Issue by alfligno** [codota/tabnine-sublime#93]
When selecting suggested line of code, other pieces of it are missing,
![ezgif com-gif-maker](https://user-images.githubusercontent.com/69491106/101855431-5ad96400-3b9e-11eb-84de-1d89a52cb783.gif)

**Comment by dimacodota** [comment]
fixed in https://github.com/codota/tabnine-sublime/releases/tag/3.0.14
