### ISSUE TITLE
Port to ST4

### ISSUE THREAD

**Issue by AmjadHD** [codota/tabnine-sublime#94]
I wanted you to be aware of the fact that a limited alpha release of Sublime Text build 4000+ is happening for over a year now, and among the many new features is a practically reworked auto-completion system that provides more capabilities for plugins, used mainly by the [LSP](https://github.com/sublimelsp/LSP) plugin
A sample of LSP using the new AC API:
![ST4LSPAC](https://user-images.githubusercontent.com/33235928/102199870-6e4d3d80-3ec4-11eb-9a62-795b3b7ee886.png)

Notes:
ST4's changelog: https://gist.github.com/jfcherng/7bf4103ea486d1f67b7970e846b3a619

**Comment by IPWright83** [comment]
Yeah, I've just tried upgrading to Sublime Text 4 and TabNine certainly doesn't play nicely in a TypeScript file.

**Comment by chendesheng** [comment]
I opened a pull request just now, check it if interest.
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/2094891/122335654-3192f980-cf6e-11eb-866c-31e6be525d6a.png">

**Comment by dimacodota** [comment]
released in [3.2.0](https://github.com/codota/tabnine-sublime/releases/tag/3.2.0)

**Comment by rwols** [comment]
I haven't watched the changes closely but wouldn't you want to make use of the async/promise API? This still seems like it's trying to emulate a state machine.
